### ISSUE TITLE
Please can you fill the readme ? 

### ISSUE THREAD

**Issue by anisayari** [betagouv/euphrosyne#41]
Hello, 

I would like to know more about this project, but the code and the repo is not understandable for an external person, can you please fill the Readme in order to permit to everyone to access to this public project ? 

Thank you

**Comment by wiwski** [comment]
Hello @anisayari,

Thank you for your interest in Euphrosyne. We just started development of the project and we will create the readme shortly.
Can you tell us more about your interest in the project ?

Cheers
